// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Steego.Demo")>]
[<assembly: AssemblyProductAttribute("Steego.Demo")>]
[<assembly: AssemblyDescriptionAttribute("A demo libray")>]
[<assembly: AssemblyVersionAttribute("1.0.2")>]
[<assembly: AssemblyFileVersionAttribute("1.0.2")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Steego.Demo"
    let [<Literal>] AssemblyProduct = "Steego.Demo"
    let [<Literal>] AssemblyDescription = "A demo libray"
    let [<Literal>] AssemblyVersion = "1.0.2"
    let [<Literal>] AssemblyFileVersion = "1.0.2"
    let [<Literal>] AssemblyConfiguration = "Release"
